# Generated by Django 5.1 on 2024-12-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='editor',
            field=models.CharField(default='unbekannt', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardware',
            name='time',
            field=models.TimeField(auto_now_add=True, default='00:00:00'),
            preserve_default=False,
        ),
    ]
